version: '3'

services:
  client:
    image: kevinduy/reactjs
    tty: true
    restart: always
    volumes:
      - ./client:/var/www/client
    working_dir: /var/www/client
    ports:
      - "3000:3000"
      - "4000:4000"
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  app:
    image: kevinduy/php
    tty: true
    restart: always
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    links:
      - db
  nginx:
    image: kevinduy/nginx
    tty: true
    restart: always
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx:/etc/nginx/conf.d
    working_dir: /var/www/app
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "nginx"
  db:
    image: mysql:5.7
    volumes:
      - .docker/mysql:/var/lib/mysql
      - .docker/data:/var/data
    working_dir: /var/data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: f5
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_USER_CONFIG_BASE64: PD9waHAKJGNmZ1snTG9naW5Db29raWVWYWxpZGl0eSddID0gODY0MDA7
